fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -87,18 +87,18 @@ jobs:
             sleep 1
           done
 
-          echo "?? Testing connection with kubectl..."
-          kubectl --kubeconfig ~/.kube/config cluster-info --insecure-skip-tls-verify
-          echo "? Exit code: $?"
+#          echo "?? Testing connection with kubectl..."
+#          kubectl --kubeconfig ~/.kube/config cluster-info --insecure-skip-tls-verify
+#          echo "? Exit code: $?"
 
           # Ïðîâåðÿåì äîñòóïíîñòü Kubernetes API — ÎÁßÇÀÒÅËÜÍÎ ñ --kubeconfig
-          echo "?? Checking Kubernetes API..."
-          if kubectl --kubeconfig ~/.kube/config get componentstatuses --insecure-skip-tls-verify --no-headers 2>/dev/null | grep -q "Healthy"; then
-            echo "? Kubernetes API is available!"
-          else
-            echo "? Kubernetes API is not reachable!"
-            exit 1
-          fi
+#          echo "?? Checking Kubernetes API..."
+#          if kubectl --kubeconfig ~/.kube/config get componentstatuses --insecure-skip-tls-verify --no-headers 2>/dev/null | grep -q "Healthy"; then
+#            echo "? Kubernetes API is available!"
+#          else
+#            echo "? Kubernetes API is not reachable!"
+#            exit 1
+#          fi
 
 
       - name: Deploy with Helm
